name: CI/CD with Github Actions de Tienda de Perritos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
      
      - name: Build Image
        run: |
          docker build -t tienda-de-perritos .

      - name: Tag Image
        run: |
          docker tag tienda-de-perritos:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tienda-de-perritos:latest

      - name: Push Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tienda-de-perritos:latest